import streamlit as st
import pdfplumber
import re
import pandas as pd
from io import BytesIO
from openpyxl.styles import Font, Alignment, PatternFill
from datetime import datetime
import plotly.express as px
from fpdf import FPDF

# ---------------- PAGE CONFIG ----------------
st.set_page_config(page_title="PF AI Command Center", layout="wide", page_icon="📊")

# ---------------- ULTRA STYLISH UI ----------------
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap');
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    .stApp { background: radial-gradient(circle at 20% 20%, #0f172a 0%, #020617 100%); color: #f8fafc; }
    .header-card {
        background: linear-gradient(135deg, rgba(30, 41, 59, 0.7), rgba(15, 23, 42, 0.8));
        padding: 40px; border-radius: 28px; border: 1px solid rgba(255, 255, 255, 0.1);
        backdrop-filter: blur(20px); text-align: center; margin-bottom: 30px;
    }
    .main-title {
        background: linear-gradient(90deg, #38bdf8, #60a5fa, #34d399);
        -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        font-weight: 800; font-size: 3rem;
    }
    .stButton>button {
        background: linear-gradient(90deg, #2563eb, #0ea5e9);
        color: white !important; border: none; border-radius: 14px;
        font-weight: 800; height: 55px; width: 100%;
    }
    [data-testid="stMetric"] {
        background: rgba(30, 41, 59, 0.6); border: 1px solid rgba(255, 255, 255, 0.1);
        padding: 20px; border-radius: 20px;
    }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="header-card">
    <div class="main-title">PF CHALLAN AI COMMAND CENTER</div>
    <div style="color: #94a3b8; font-size: 1.1rem; font-weight: 600; margin-top:10px;">ENTERPRISE AUDIT SUITE BY ABHISHEK JAKKULA</div>
    <div style="color: #facc15; font-style: italic; margin-top: 15px;">🌸 Lord Krishna Blessings: कर्मण्येवाधिकारस्ते मा फलेषु कदाचन 🌸</div>
</div>
""", unsafe_allow_html=True)

# ---------------- HELPERS ----------------
def safe_extract(pattern, text):
    m = re.search(pattern, text, re.I | re.M)
    if m:
        val = m.group(1).replace(",", "").strip()
        return val if val else "0"
    return "0"

def calculate_due_date(wage_month_str):
    try:
        parts = wage_month_str.split()
        month_dt = datetime.strptime(parts[0], "%B")
        year = int(parts[1])
        next_m = month_dt.month % 12 + 1
        next_y = year + (1 if month_dt.month == 12 else 0)
        return datetime(next_y, next_m, 15)
    except: return None

# ---------------- EXPORT ENGINES ----------------
def to_excel_pro(df):
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='PF_Audit')
        ws = writer.sheets['PF_Audit']
        h_fill, h_font = PatternFill(start_color="1e293b", end_color="1e293b", fill_type="solid"), Font(bold=True, color="FFFFFF")
        for cell in ws[1]:
            cell.font, cell.fill, cell.alignment = h_font, h_fill, Alignment(horizontal="center")
        for col in ws.columns:
            max_len = max([len(str(cell.value)) for cell in col])
            ws.column_dimensions[col[0].column_letter].width = max_len + 3
    return output.getvalue()

def generate_pdf_summary(df, total_pf, emp_dis, emplr_dis):
    pdf = FPDF(orientation='L', unit='mm', format='A4')
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "STATUTORY PF COMPLIANCE AUDIT CERTIFICATE", ln=True, align='C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, f"Generated by Abhishek Jakkula | {datetime.now().strftime('%d-%m-%Y')}", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, f"Total Audited: INR {total_pf:,.2f}", ln=True)
    pdf.cell(0, 8, f"Total Employee Disallowance: INR {emp_dis:,.2f}", ln=True)
    pdf.cell(0, 8, f"Total Employer Disallowance (Late): INR {emplr_dis:,.2f}", ln=True)
    pdf.ln(5)

    pdf.set_font("Arial", 'B', 8); pdf.set_fill_color(30, 41, 59); pdf.set_text_color(255, 255, 255)
    w = [30, 25, 25, 12, 22, 28, 28, 28, 28, 28, 18] 
    headers = ["Wage Month", "Due Date", "Paid Date", "Diff", "Admin", "Employer", "Employee", "Total", "Emp Dis", "Emplr Dis", "Status"]
    for i in range(len(headers)): pdf.cell(w[i], 10, headers[i], 1, 0, 'C', True)
    pdf.ln()

    pdf.set_font("Arial", '', 7); pdf.set_text_color(0, 0, 0)
    for _, row in df.iterrows():
        pdf.cell(w[0], 8, str(row['Wage Month']), 1)
        pdf.cell(w[1], 8, str(row['Due Date']), 1, 0, 'C')
        pdf.cell(w[2], 8, str(row['Generated Date']), 1, 0, 'C')
        pdf.cell(w[3], 8, str(row['Late Days']), 1, 0, 'C')
        pdf.cell(w[4], 8, f"{row['Admin Charges']:,.2f}", 1, 0, 'R')
        pdf.cell(w[5], 8, f"{row['Employer Share']:,.2f}", 1, 0, 'R')
        pdf.cell(w[6], 8, f"{row['Employee Share']:,.2f}", 1, 0, 'R')
        pdf.cell(w[7], 8, f"{row['Grand Total']:,.2f}", 1, 0, 'R')
        pdf.cell(w[8], 8, f"{row['Employee Disallowance']:,.2f}", 1, 0, 'R')
        pdf.cell(w[9], 8, f"{row['Employer Disallowance']:,.2f}", 1, 0, 'R')
        pdf.cell(w[10], 8, "LATE" if row['Late Days'] > 0 else "OK", 1, 1, 'C')
    
    return pdf.output(dest='S').encode('latin-1', 'replace')

# ---------------- MAIN APP ----------------
files = st.file_uploader("📂 Upload PF Challan PDFs", type="pdf", accept_multiple_files=True)
run = st.button("🚀 INITIATE SYSTEM AUDIT")

if files and run:
    all_data = []
    for f in files:
        with pdfplumber.open(f) as pdf:
            text = "\n".join([p.extract_text() for p in pdf.pages if p.extract_text()])
            blocks = re.split(r"(Dues for the wage month of\s*[A-Za-z]+\s*[0-9]{4})", text, flags=re.I)
            
            for i in range(1, len(blocks), 2):
                content = blocks[i] + blocks[i+1]
                m_match = re.search(r"wage month of\s*([A-Za-z]+)\s*([0-9]{4})", content, re.I)
                wage_month = f"{m_match.group(1).title()} {m_match.group(2)}" if m_match else "Unknown"
                
                gen_date_str = safe_extract(r"system generated challan on\s*.*?(\d{2}-[A-Z]{3}-\d{4})", content).upper()
                due_dt = calculate_due_date(wage_month)
                
                # Financial Data from TOTAL Column on far right ($ anchor)
                admin = float(safe_extract(r"Administration Charges\s+.*?\s+(\d[\d,.]*)$", content))
                employer = float(safe_extract(r"Employer'?s Share Of\s+.*?\s+(\d[\d,.]*)$", content))
                employee = float(safe_extract(r"Employee'?s Share Of\s+.*?\s+(\d[\d,.]*)$", content))
                total_val = float(safe_extract(r"Grand Total\s*:\s*.*?\s+(\d[\d,.]*)$", content))
                
                # Late Days: Negative is Early, Positive is Late
                diff = 0
                if due_dt and gen_date_str != "0":
                    try:
                        # Fixed format logic to avoid ValueError
                        gen_dt = datetime.strptime(gen_date_str, "%d-%b-%Y")
                        diff = (gen_dt - due_dt).days
                    except: pass
                
                all_data.append({
                    "Wage Month": wage_month, "Due Date": due_dt.strftime("%d-%b-%Y") if due_dt else "N/A",
                    "Generated Date": gen_date_str, "Late Days": diff,
                    "Admin Charges": admin, "Employer Share": employer, "Employee Share": employee,
                    "Grand Total": total_val, 
                    "Employee Disallowance": employee if diff > 0 else 0.0,
                    "Employer Disallowance": employer if diff > 0 else 0.0
                })

    if all_data:
        df = pd.DataFrame(all_data)
        st.markdown("### 📊 AUDIT DASHBOARD")
        m1, m2, m3 = st.columns(3)
        m1.metric("TOTAL PF PAID", f"INR {df['Grand Total'].sum():,.2f}")
        total_dis = df['Employee Disallowance'].sum() + df['Employer Disallowance'].sum()
        m2.metric("TOTAL DISALLOWANCE", f"INR {total_dis:,.2f}", delta_color="inverse")
        m3.metric("LATE FILINGS", len(df[df['Late Days'] > 0]))

        st.markdown("---")
        fig = px.bar(df, x='Wage Month', y='Grand Total', color='Late Days', title="PF Trends & Payment Performance")
        fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", font=dict(color="white"))
        st.plotly_chart(fig, use_container_width=True)

        c1, c2 = st.columns(2)
        with c1: st.download_button("🚀 DOWNLOAD EXCEL AUDIT", to_excel_pro(df), "PF_Audit_Report.xlsx")
        with c2: 
            pdf_raw = generate_pdf_summary(df, df['Grand Total'].sum(), df['Employee Disallowance'].sum(), df['Employer Disallowance'].sum())
            st.download_button("📜 DOWNLOAD PDF AUDIT TRAIL", pdf_raw, "PF_Audit_Trail.pdf", "application/pdf")

        st.dataframe(df.style.format({"Grand Total": "{:,.2f}", "Employee Disallowance": "{:,.2f}", "Employer Disallowance": "{:,.2f}"}), use_container_width=True)

st.caption("© 2026 | Developed by Abhishek Jakkula")
