import streamlit as st
import pdfplumber
import re
import pandas as pd
from io import BytesIO
from openpyxl.styles import Font, Alignment, PatternFill
from datetime import datetime
import plotly.express as px
from fpdf import FPDF

# ---------------- PAGE CONFIG ----------------
st.set_page_config(page_title="PF AI Command Center", layout="wide", page_icon="📊")

# ---------------- ULTRA STYLISH UI THEME ----------------
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap');
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    .stApp { background: radial-gradient(circle at 20% 20%, #0f172a 0%, #020617 100%); color: #f8fafc; }
    .header-card {
        background: linear-gradient(135deg, rgba(30, 41, 59, 0.7), rgba(15, 23, 42, 0.8));
        padding: 40px; border-radius: 28px; border: 1px solid rgba(255, 255, 255, 0.1);
        backdrop-filter: blur(20px); text-align: center; margin-bottom: 40px;
        box-shadow: 0 25px 50px rgba(0, 0, 0, 0.4);
    }
    .main-title {
        background: linear-gradient(90deg, #38bdf8, #60a5fa, #34d399);
        -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        font-weight: 800; font-size: 3.5rem; line-height: 1.1;
    }
    .stButton>button {
        background: linear-gradient(90deg, #2563eb, #0ea5e9);
        color: white !important; border: none; border-radius: 14px;
        font-weight: 800; height: 60px; width: 100%; transition: 0.4s;
    }
    [data-testid="stMetric"] {
        background: rgba(30, 41, 59, 0.6) !important; border: 1px solid rgba(255, 255, 255, 0.1) !important;
        padding: 25px !important; border-radius: 24px !important;
    }
</style>
""", unsafe_allow_html=True)

# ---------------- BRANDED HEADER ----------------
st.markdown("""
<div class="header-card">
    <div class="main-title">PF CHALLAN AI COMMAND CENTER</div>
    <div style="color: #94a3b8; font-size: 1.1rem; letter-spacing: 2px; margin-top: 15px; font-weight: 600;">STATUTORY AUDIT & DISALLOWANCE SUITE BY ABHISHEK JAKKULA</div>
    <div style="color: #facc15; font-style: italic; margin-top: 20px; font-size: 1.1rem;">🌸 Lord Krishna Blessings: कर्मण्येवाधिकारस्ते मा फलेषु कदाचन 🌸</div>
</div>
""", unsafe_allow_html=True)

# ---------------- HELPERS ----------------
def safe_extract(pattern, text):
    m = re.search(pattern, text, re.I | re.S)
    return m.group(1).strip() if m else "0"

def calculate_due_date(wage_month_str):
    try:
        parts = wage_month_str.split()
        month_dt = datetime.strptime(parts[0], "%B")
        year = int(parts[1])
        next_m = month_dt.month % 12 + 1
        next_y = year + (1 if month_dt.month == 12 else 0)
        return datetime(next_y, next_m, 15)
    except: return None

# ---------------- EXCEL EXPORTER ----------------
def to_excel_pro(df):
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='PF_Audit_Report')
        ws = writer.sheets['PF_Audit_Report']
        h_fill, h_font = PatternFill(start_color="1e293b", end_color="1e293b", fill_type="solid"), Font(bold=True, color="FFFFFF")
        for cell in ws[1]:
            cell.font, cell.fill, cell.alignment = h_font, h_fill, Alignment(horizontal="center")
        for col in ws.columns:
            max_len = max([len(str(cell.value)) for cell in col])
            ws.column_dimensions[col[0].column_letter].width = max_len + 3
    return output.getvalue()

# ---------------- PDF GENERATOR (FIXED ENCODING) ----------------
def generate_pdf_summary(df, total_pf, disallowance):
    pdf = FPDF(orientation='L', unit='mm', format='A4')
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "STATUTORY PF COMPLIANCE AUDIT CERTIFICATE", ln=True, align='C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, f"Generated by: Abhishek Jakkula Audit Engine | {datetime.now().strftime('%d-%m-%Y')}", ln=True, align='C')
    pdf.ln(10)
    
    # Summary Info (Removed Rupee symbol to prevent crash)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"Total Amount Audited: INR {total_pf:,.2f} | Disallowance: INR {disallowance:,.2f}", ln=True)
    pdf.ln(5)

    # Table Header
    pdf.set_font("Arial", 'B', 8); pdf.set_fill_color(30, 41, 59); pdf.set_text_color(255, 255, 255)
    w = [30, 25, 25, 15, 25, 30, 30, 30, 30, 20] 
    headers = ["Wage Month", "Due Date", "Paid Date", "Late", "Admin", "Employer", "Employee", "Total", "Disallowance", "Status"]
    for i in range(len(headers)): pdf.cell(w[i], 10, headers[i], 1, 0, 'C', True)
    pdf.ln()

    # Table Rows
    pdf.set_font("Arial", '', 7); pdf.set_text_color(0, 0, 0)
    for _, row in df.iterrows():
        pdf.cell(w[0], 8, str(row['Wage Month']), 1)
        pdf.cell(w[1], 8, str(row['Due Date']), 1, 0, 'C')
        pdf.cell(w[2], 8, str(row['Generated Date']), 1, 0, 'C')
        pdf.cell(w[3], 8, str(row['Late Days']), 1, 0, 'C')
        pdf.cell(w[4], 8, f"{row['Admin Charges (INR)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[5], 8, f"{row['Employer Share (INR)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[6], 8, f"{row['Employee Share (INR)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[7], 8, f"{row['Grand Total (INR)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[8], 8, f"{row['PF Disallowance (INR)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[9], 8, "LATE" if row['Late Days'] > 0 else "OK", 1, 1, 'C')
    
    return pdf.output(dest='S').encode('latin-1', 'replace')

# ---------------- COMMAND CENTER ----------------
col_f, col_a = st.columns([2, 1])
with col_f: files = st.file_uploader("📂 DROP PF CHALLAN PDFs HERE", type="pdf", accept_multiple_files=True)
with col_a: 
    st.markdown("<br>", unsafe_allow_html=True)
    run_audit = st.button("🚀 INITIATE SYSTEM AUDIT")

if files and run_audit:
    all_rows = []
    for f in files:
        with pdfplumber.open(f) as pdf:
            text = "\n".join([p.extract_text() for p in pdf.pages if p.extract_text()])
            # Enhanced regex splitting for standard EPFO digital challans
            blocks = re.split(r"(Dues for the wage month of\s*[A-Za-z]+\s*[0-9]{4})", text, flags=re.I)
            for i in range(1, len(blocks), 2):
                content = blocks[i] + blocks[i+1]
                m_match = re.search(r"wage month of\s*([A-Za-z]+)\s*([0-9]{4})", content, re.I)
                wage_month = f"{m_match.group(1).title()} {m_match.group(2)}" if m_match else "Unknown"
                sys_date_str = safe_extract(r"system generated challan on\s*.*?(\d{2}-[A-Z]{3}-\d{4})", content).upper()
                due_dt = calculate_due_date(wage_month)
                emp_share = float(safe_extract(r"Employee'?s Share Of.*?([0-9,]{2,})", content).replace(",", ""))
                
                # Late Days Logic: Positive = Late, Negative = Early
                late_days = (datetime.strptime(sys_date_str, "%d-%b-%Y") - due_dt).days if due_dt and sys_date_str != "0" else 0
                
                all_rows.append({
                    "Wage Month": wage_month, "Due Date": due_dt.strftime("%d-%b-%Y") if due_dt else "N/A",
                    "Generated Date": sys_date_str, "Late Days": late_days,
                    "Admin Charges (INR)": float(safe_extract(r"Administration Charges.*?([0-9,]{2,})", content).replace(",", "")),
                    "Employer Share (INR)": float(safe_extract(r"Employer'?s Share Of.*?([0-9,]{2,})", content).replace(",", "")),
                    "Employee Share (INR)": emp_share, "PF Disallowance (INR)": emp_share if late_days > 0 else 0.0,
                    "Grand Total (INR)": float(safe_extract(r"Grand Total.*?([0-9,]{2,})", content).replace(",", ""))
                })

    if all_rows:
        df = pd.DataFrame(all_rows)
        total_pf, total_dis = df['Grand Total (INR)'].sum(), df['PF Disallowance (INR)'].sum()
        
        st.markdown("### 📊 STATUTORY COMMAND INSIGHTS")
        m1, m2, m3 = st.columns(3)
        m1.metric("TOTAL PF AUDITED", f"INR {total_pf:,.2f}")
        m2.metric("TAX DISALLOWANCE", f"INR {total_dis:,.2f}", delta=f"Risk: {total_dis*0.3:,.0f}", delta_color="inverse")
        m3.metric("LATE FILINGS", len(df[df['Late Days'] > 0]))

        st.markdown("---")
        c1, c2 = st.columns([1.5, 1])
        with c1:
            fig = px.bar(df, x='Wage Month', y='Grand Total (INR)', color='Late Days', title="PF Contribution Trend & Delay Tracker")
            fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", font=dict(color="white"))
            st.plotly_chart(fig, use_container_width=True)
        with c2:
            st.markdown("#### 📥 EXPORT COMMANDS")
            st.download_button("🚀 DOWNLOAD EXCEL AUDIT", to_excel_pro(df), f"PF_Audit_{datetime.now().year}.xlsx")
            pdf_data = generate_pdf_summary(df, total_pf, total_dis)
            st.download_button("📜 DOWNLOAD PDF AUDIT TRAIL", pdf_data, "PF_Audit_Trail.pdf", "application/pdf")

        st.dataframe(df.style.format({"Grand Total (INR)": "{:,.2f}", "PF Disallowance (INR)": "{:,.2f}", "Employee Share (INR)": "{:,.2f}", "Admin Charges (INR)": "{:,.2f}"}), use_container_width=True)
    else:
        st.error("❌ NO DATA FOUND: Ensure the PDF is an original digital EPFO challan receipt.")

st.caption("© 2026 | Enterprise Auditor Pro | Developed by Abhishek Jakkula | jakkulaabhishek5@gmail.com")
