import streamlit as st
import pdfplumber
import re
import pandas as pd
from io import BytesIO
from openpyxl.styles import Font, Alignment, PatternFill
from datetime import datetime
import plotly.express as px
from fpdf import FPDF

# ---------------- PAGE CONFIG ----------------
st.set_page_config(page_title="Abhishek Jakkula | PF AI Auditor", layout="wide", page_icon="📊")

# ---------------- ENTERPRISE UI THEME ----------------
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap');
    
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    
    /* Deep Professional Background */
    .stApp {
        background: radial-gradient(circle at 20% 20%, #0f172a 0%, #020617 100%);
        color: #f8fafc;
    }

    /* Sidebar Styling */
    section[data-testid="stSidebar"] {
        background-color: rgba(15, 23, 42, 0.8) !important;
        border-right: 1px solid rgba(255, 255, 255, 0.1);
    }

    /* Glassmorphism Header Card */
    .header-card {
        background: linear-gradient(135deg, rgba(30, 41, 59, 0.7), rgba(15, 23, 42, 0.8));
        padding: 40px;
        border-radius: 24px;
        border: 1px solid rgba(255, 255, 255, 0.1);
        backdrop-filter: blur(20px);
        text-align: center;
        margin-bottom: 40px;
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);
    }

    .main-title {
        background: linear-gradient(90deg, #38bdf8, #60a5fa, #34d399);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: 800;
        font-size: 3.2rem;
        letter-spacing: -1px;
    }

    /* Metric Cards */
    [data-testid="stMetric"] {
        background: rgba(30, 41, 59, 0.5) !important;
        border: 1px solid rgba(255, 255, 255, 0.1) !important;
        padding: 24px !important;
        border-radius: 20px !important;
        backdrop-filter: blur(10px);
    }

    /* Action Buttons */
    .stButton>button {
        background: linear-gradient(90deg, #2563eb, #0ea5e9);
        color: white !important;
        border: none;
        border-radius: 12px;
        font-weight: 700;
        height: 54px;
        width: 100%;
        transition: all 0.3s ease;
        text-transform: uppercase;
        letter-spacing: 1px;
    }

    .stButton>button:hover {
        transform: translateY(-2px);
        box-shadow: 0 10px 20px rgba(37, 99, 235, 0.4);
    }
</style>
""", unsafe_allow_html=True)

# ---------------- HELPERS ----------------
def safe_extract(pattern, text):
    m = re.search(pattern, text, re.I | re.S)
    return m.group(1).strip() if m else "0"

def calculate_due_date(wage_month_str):
    try:
        parts = wage_month_str.split()
        month_dt = datetime.strptime(parts[0], "%B")
        year = int(parts[1])
        next_m = month_dt.month % 12 + 1
        next_y = year + (1 if month_dt.month == 12 else 0)
        return datetime(next_y, next_m, 15)
    except: return None

# ---------------- PDF GENERATOR ----------------
def generate_pdf_summary(df, total_pf, disallowance, late_count):
    pdf = FPDF(orientation='L', unit='mm', format='A4')
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "STATUTORY PF COMPLIANCE AUDIT", ln=True, align='C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, f"Generated by: Abhishek Jakkula Audit Suite | {datetime.now().strftime('%d-%m-%Y')}", ln=True, align='C')
    pdf.ln(10)
    
    # Header Styling
    pdf.set_font("Arial", 'B', 9)
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    
    w = [30, 25, 25, 20, 35, 35, 35, 25, 35] 
    headers = ["Wage Month", "Due Date", "Paid Date", "Late", "Employer ₹", "Employee ₹", "Total ₹", "Status", "Disallowance"]
    
    for i in range(len(headers)):
        pdf.cell(w[i], 10, headers[i], 1, 0, 'C', True)
    pdf.ln()

    pdf.set_font("Arial", '', 8)
    pdf.set_text_color(0, 0, 0)
    for index, row in df.iterrows():
        pdf.cell(w[0], 8, str(row['Wage Month']), 1)
        pdf.cell(w[1], 8, str(row['Due Date']), 1, 0, 'C')
        pdf.cell(w[2], 8, str(row['Generated Date']), 1, 0, 'C')
        pdf.cell(w[3], 8, str(row['Late Days']), 1, 0, 'C')
        pdf.cell(w[4], 8, f"{row['Employer Share (₹)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[5], 8, f"{row['Employee Share (₹)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[6], 8, f"{row['Grand Total (₹)']:,.2f}", 1, 0, 'R')
        pdf.cell(w[7], 8, "Late" if row['Late Days'] > 0 else "On Time", 1, 0, 'C')
        pdf.cell(w[8], 8, f"{row['PF Disallowance (₹)']:,.2f}", 1, 1, 'R')
    
    return pdf.output(dest='S').encode('latin-1')

# ---------------- BRANDED SIDEBAR ----------------
with st.sidebar:
    st.markdown("### 🛠️ AUDIT SETTINGS")
    st.info("Ensure PDF files are original EPFO receipts for 100% accuracy.")
    st.markdown("---")
    st.markdown("### 👤 DEVELOPER")
    st.write("**Abhishek Jakkula**")
    st.write("jakkulaabhishek5@gmail.com")

# ---------------- MAIN HEADER ----------------
st.markdown("""
<div class="header-card">
    <div class="main-title">PF CHALLAN COMMAND CENTER</div>
    <div style="color: #94a3b8; font-size: 1.1rem; letter-spacing: 2px; margin-top: 10px; font-weight: 600;">
        ENTERPRISE COMPLIANCE & STATUTORY AUDIT SUITE
    </div>
    <div style="color: #facc15; font-style: italic; margin-top: 20px; font-size: 1rem;">
        🌸 Lord Krishna Blessings: कर्मण्येवाधिकारस्ते मा फलेषु कदाचन 🌸
    </div>
</div>
""", unsafe_allow_html=True)

# ---------------- FILE UPLOAD ----------------
col_upload, col_action = st.columns([2, 1])
with col_upload:
    files = st.file_uploader("📂 DROP PF CHALLAN PDFs HERE", type="pdf", accept_multiple_files=True)
with col_action:
    st.markdown("<br>", unsafe_allow_html=True)
    run_audit = st.button("🚀 INITIATE SYSTEM AUDIT")

# ---------------- AUDIT ENGINE ----------------
if files and run_audit:
    all_rows = []
    for f in files:
        with pdfplumber.open(f) as pdf:
            text = "\n".join([p.extract_text() for p in pdf.pages if p.extract_text()])
            blocks = re.split(r"(Dues for the wage month of\s*[A-Za-z]+\s*[0-9]{4})", text, flags=re.I)
            for i in range(1, len(blocks), 2):
                content = blocks[i] + blocks[i+1]
                m_match = re.search(r"wage month of\s*([A-Za-z]+)\s*([0-9]{4})", content, re.I)
                wage_month = f"{m_match.group(1).title()} {m_match.group(2)}" if m_match else "Unknown"
                sys_date_str = safe_extract(r"system generated challan on\s*.*?(\d{2}-[A-Z]{3}-\d{4})", content).upper()
                due_dt = calculate_due_date(wage_month)
                late_days, disallowance, emp_share = 0, 0.0, float(safe_extract(r"Employee'?s Share Of.*?([0-9,]{2,})", content).replace(",", ""))
                
                if due_dt and sys_date_str != "0":
                    try:
                        gen_dt = datetime.strptime(sys_date_str, "%d-%b-%Y")
                        if gen_dt > due_dt:
                            late_days = (gen_dt - due_dt).days
                            disallowance = emp_share
                    except: pass
                
                all_rows.append({
                    "Wage Month": wage_month, "Due Date": due_dt.strftime("%d-%b-%Y") if due_dt else "N/A",
                    "Generated Date": sys_date_str, "Late Days": late_days,
                    "Employer Share (₹)": float(safe_extract(r"Employer'?s Share Of.*?([0-9,]{2,})", content).replace(",", "")),
                    "Employee Share (₹)": emp_share, "PF Disallowance (₹)": disallowance,
                    "Grand Total (₹)": float(safe_extract(r"Grand Total.*?([0-9,]{2,})", content).replace(",", ""))
                })

    if all_rows:
        df = pd.DataFrame(all_rows)
        
        # Dashboard Visuals
        st.markdown("### 📊 STATUTORY DASHBOARD")
        d1, d2, d3 = st.columns(3)
        d1.metric("TOTAL PF AUDITED", f"₹{df['Grand Total (₹)'].sum():,.2f}")
        total_dis = df['PF Disallowance (₹)'].sum()
        d2.metric("TAX DISALLOWANCE", f"₹{total_dis:,.2f}", delta=f"Risk: ₹{total_dis*0.3:,.0f}", delta_color="inverse")
        d3.metric("LATE FILINGS", len(df[df['Late Days'] > 0]))

        st.markdown("---")
        
        # Downloads
        dl1, dl2 = st.columns(2)
        with dl1:
            st.download_button("📥 DOWNLOAD EXCEL AUDIT", df.to_csv().encode('utf-8'), "PF_Audit.csv")
        with dl2:
            pdf_data = generate_pdf_summary(df, df['Grand Total (₹)'].sum(), total_dis, len(df[df['Late Days'] > 0]))
            st.download_button("📜 DOWNLOAD PDF AUDIT TRAIL", pdf_data, "PF_Audit_Trail.pdf", "application/pdf")

        st.dataframe(df.style.format({"Grand Total (₹)": "{:,.2f}", "PF Disallowance (₹)": "{:,.2f}"}), use_container_width=True)

st.caption("© 2026 | Enterprise Auditor Pro | Developed by Abhishek Jakkula")
